### ISSUE TITLE
Display a helpful error message when the required credentials aren't set

### ISSUE THREAD

**Issue by mdb** [Comcast/akamai-gtm#3]
In current implementation, if the `AKAMAI_EDGEGRID_HOST`, `AKAMAI_EDGEGRID_CLIENT_TOKEN`, `AKAMAI_EDGEGRID_ACCESS_TOKEN`, and `AKAMAI_EDGEGRID_CLIENT_SECRET` environment variables are not set -- nor passed as parameters -- `akamai-gtm` fails in an obtuse way. Instead, some instructive output should be displayed informing the user of the required parameters.

Example:

```
$ akamai-gtm properties foo.akadns.net
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xd90bd]

goroutine 1 [running]:
panic(0x4194a0, 0x82077a1d0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
github.com/codegangsta/cli.HandleAction.func1(0x8208870d8)
        /home/travis/gopath/src/github.com/codegangsta/cli/app.go:478 +0x38e
panic(0x4194a0, 0x82077a1d0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
github.com/comcast/go-edgegrid/edgegrid.resourceRequest(0x88207bc860, 0x82077b940, 0x49efa8, 0x3, 0x820780f40, 0x34, 0x0, 0x0, 0x0, 0x439320, ...)
        /home/travis/gopath/src/github.com/comcast/go-edgegrid/edgegrid/util.go:62 +0xa0d
github.com/comcast/go-edgegrid/edgegrid.(*GTMClient).Properties(0x82077b940, 0x7fff5fbfecd9, 0x12, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/comcast/go-edgegrid/edgegrid/gtm_client_api.go:144 +0x168
main.properties(0x82081e8c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Comcast/akamai-gtm/akamai.go:504 +0x168
reflect.Value.call(0x379de0, 0x563de8, 0x13, 0x49ea90, 0x4, 0x820887058, 0x1, 0x1, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x379de0, 0x563de8, 0x13, 0x820887058, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.6.linux.amd64/src/reflect/value.go:303 +0xb1
github.com/codegangsta/cli.HandleAction(0x379de0, 0x563de8, 0x82081e8c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/codegangsta/cli/app.go:487 +0x2ee
github.com/codegangsta/cli.Command.Run(0x4b0970, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4b0970, 0xa, 0x0, ...)
        /home/travis/gopath/src/github.com/codegangsta/cli/command.go:189 +0xf1b
github.com/codegangsta/cli.(*App).Run(0x82076af00, 0x8207e21b0, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/codegangsta/cli/app.go:240 +0xaa4
main.main()
        /home/travis/gopath/src/github.com/Comcast/akamai-gtm/akamai.go:256 +0x202a
```

**Comment by jgarrouste** [comment]
Same result with wrong arguments : 

```
$ akamai-gtm --host testage --client_token testage --access_token testage --client_secret testage properties foo.akadns.net
 ```
